### PR TITLE
Update all_pattern_test.rb

### PR DESCRIPTION
**Pull request by neslom**
remove duplicate test names

### CODE REVIEW

**Comment by kytrinyx** [comment]
Good catch, thanks!

The error needs to be fixed in the generator: https://github.com/turingschool/enums-exercises/blob/master/lib/generator/all_problem.rb#L27 - and then the problem needs to be regenerated. Want to give it a whirl?

**Comment by neslom** [comment]
Yes

**Comment by neslom** [comment]
Hey Katrina,

   Would you like to leave the enums-exercise repository as it is, so that
us students can see how we would go about changing the generator file and
regenerating the problems , or would you prefer I fix it as the readme
instructs and submit a pull request?

   Sorry for the questions - I'm still pretty new to this. I hope you're
having a great new year!

Markus

**Comment by kytrinyx** [comment]
I think it would be best to fix the generator and regenerate the exercises, so that they're exactly what people need.

An additional pull request to tweak the README would also be great, if you have any ideas there.

Thanks :)

**Pull request closed without merging**
